#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username postgres <<-EOSQL
    CREATE ROLE API_USER_ROLE;
    CREATE ROLE MIGRATOR_ROLE WITH SUPERUSER CREATEROLE ;
    CREATE USER auth WITH password 'auth_pass' ROLE API_USER_ROLE;
    CREATE USER auth_migrator WITH password 'auth_pass_migrator' ROLE MIGRATOR_ROLE;
    CREATE DATABASE auth;
    GRANT ALL PRIVILEGES ON DATABASE auth TO API_USER_ROLE;
    GRANT ALL PRIVILEGES ON DATABASE auth TO MIGRATOR_ROLE;
EOSQL
